ignore:
  - "crates/libduckdb-sys/duckdb"
  - "crates/libduckdb-sys/src/bindgen_bundled_version.rs"
coverage:
  status:
    project:
      default:
        informational: true
    patch:
      default:
        informational: true
