version: 2
updates:
  - package-ecosystem: cargo
    directory: "/"
    schedule:
      interval: daily
    allow:
      - dependency-type: direct
    open-pull-requests-limit: 10
    target-branch: main
    labels: [auto-dependencies]
  - package-ecosystem: rust-toolchain
    directory: "/"
    schedule:
      interval: daily
    target-branch: main
    labels: [auto-dependencies]
