[workspace]
resolver = "3"
members = [
    "crates/duckdb",
    "crates/libduckdb-sys",
]

[workspace.package]
version = "2.0.0"
authors = ["DuckDB Labs and contributors", "wangfenjin <wangfenj@gmail.com>"]
repository = "https://github.com/duckdb/duckdb-rs"
homepage = "https://github.com/duckdb/duckdb-rs"
documentation = "https://docs.rs/duckdb/"
readme = "README.md"
keywords = ["duckdb", "database", "ffi"]
license = "MIT"
categories = ["database"]
edition = "2024"
rust-version = "1.85.1"
