[package]
name = "duckdb-rs"
description = "Ergonomic wrapper for DuckDB"
# ---
version = { workspace = true }
authors = { workspace = true }
license = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
categories = { workspace = true }
keywords = { workspace = true }
readme = { workspace = true }
edition = { workspace = true }
rust-version = { workspace = true }

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(coverage_nightly)'] }

[features]
capi-v2-p2 = []
r2d2 = ["dep:r2d2"]

[dependencies]
libc = "0.2.186"
libduckdb-sys = { version = "2.0.0", path = "../libduckdb-sys" }
paste = "1.0.15"
r2d2 = {version = "0.8.10", optional = true }
