[package]
name = "duckdb-rs"
description = "Ergonomic wrapper for DuckDB"
# ---
version = { workspace = true }
authors = { workspace = true }
license = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
categories = { workspace = true }
keywords = { workspace = true }
readme = { workspace = true }
edition = { workspace = true }
rust-version = { workspace = true }

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(coverage_nightly)'] }

[features]
# Forward static linking down to libduckdb-sys.
bundled = ["libduckdb-sys/bundled"]
strict-docs = []
capi-v2-p2 = []

[dependencies]
libc = "0.2.186"
libduckdb-sys = { version = "2.0.0", path = "../libduckdb-sys" }
paste = "1.0.15"
