//! Catalog metadata for a resolved base table.

use libduckdb_sys as ffi;

use crate::{
    Connection, Parameters, Result, check_api_call, check_api_call_no_err, qualified_name::QualifiedName,
    schema::Schema,
};

/// An owned snapshot of a base table's catalog metadata.
///
/// The snapshot records the fully resolved name, columns, and per-column
/// properties at creation time; later DDL does not update it. Column property
/// indices align with the fields returned by [`Self::schema`].
///
/// # Example
/// ```
/// use duckdb_rs::{Environment, StorageLocation, Parameters};
/// use duckdb_rs::qualified_name::QualifiedName;
/// use duckdb_rs::table_description::TableDescription;
///
/// # fn main() -> duckdb_rs::Result<()> {
/// let env = Environment::new()?;
/// let db = env.open(StorageLocation::InMemory)?;
/// let conn = db.connect()?;
/// let mut statements =
///     conn.parse("CREATE TABLE items (id INTEGER, name VARCHAR DEFAULT 'unknown')")?;
/// conn.execute(
///     statements.next().expect("expected a statement")?,
///     Parameters::None,
/// )?;
///
/// let name = QualifiedName::from_sql("items")?;
/// let description = TableDescription::new(&conn, &name)?;
///
/// assert_eq!(description.schema()?.len()?, 2);
/// assert!(description.column_has_default(1)?);
/// # Ok(())
/// # }
/// ```
pub struct TableDescription {
    handle: ffi::duckdb_v2_table_description_handle,
}

impl TableDescription {
    /// Resolve a base table through the connection's catalog and search path.
    pub fn new(connection: &Connection, name: &QualifiedName) -> Result<Self> {
        Ok(TableDescription {
            handle: check_api_call!(
                ffi::duckdb_v2_table_description_create,
                connection.handle,
                name.handle,
                RET
            )?,
        })
    }

    /// Return the table's fully resolved qualified name.
    pub fn qname(&self) -> Result<QualifiedName> {
        let handle = check_api_call!(ffi::duckdb_v2_table_description_get_qname, self.handle, RET)?;

        Ok(QualifiedName { handle })
    }

    /// Return the columns in declaration order, including generated columns.
    pub fn schema(&self) -> Result<Schema> {
        let handle = check_api_call!(ffi::duckdb_v2_table_description_get_schema, self.handle, RET)?;

        Ok(Schema { handle })
    }

    /// Return whether the table belongs to a read-only catalog.
    pub fn readonly(&self) -> Result<bool> {
        check_api_call!(ffi::duckdb_v2_table_description_is_readonly, self.handle, RET)
    }

    /// Return whether a column declares a default expression.
    ///
    /// Generated columns report `false`. An out-of-range index returns an
    /// error.
    pub fn column_has_default(&self, column_index: usize) -> Result<bool> {
        check_api_call!(
            ffi::duckdb_v2_table_description_column_has_default,
            self.handle,
            column_index as u64,
            RET
        )
    }

    /// Return whether a column is generated by DuckDB.
    ///
    /// An out-of-range index returns an error.
    pub fn column_is_generated(&self, column_index: usize) -> Result<bool> {
        check_api_call!(
            ffi::duckdb_v2_table_description_column_is_generated,
            self.handle,
            column_index as u64,
            RET
        )
    }
}

impl Drop for TableDescription {
    fn drop(&mut self) {
        check_api_call_no_err!(ffi::duckdb_v2_table_description_destroy, &mut self.handle).unwrap();
    }
}

#[cfg(test)]
#[cfg_attr(coverage_nightly, coverage(off))]
mod tests {
    use crate::{Environment, StorageLocation, qualified_name::QualifiedName, table_description::TableDescription};
    #[test]
    fn test_table_description() -> crate::Result<()> {
        let env = Environment::new()?;
        let db = env.open(StorageLocation::InMemory)?;
        let conn = db.connect()?;

        let mut statements =
            conn.parse("CREATE TABLE test (id INTEGER, name VARCHAR DEFAULT \'DEF\', td AS (2*id));")?;

        conn.execute(statements.next().unwrap()?, Parameters::None)?;

        let qname = QualifiedName::from_sql("test")?;
        let table_desc = TableDescription::new(&conn, &qname)?;

        assert!(!table_desc.readonly()?);
        assert_eq!(table_desc.schema()?.len()?, 3);
        assert!(!table_desc.column_has_default(0)?);
        assert!(table_desc.column_has_default(1)?);
        assert!(!table_desc.column_is_generated(0)?);
        assert!(table_desc.column_is_generated(2)?);

        Ok(())
    }
}
